export const weatherData = [
  {
    day: "Dziś",
    hour: "7:00",
    weatherName: "foggy",
    temperature: -1,
    rains: 0,
    windDirection: 0,
    windSpeed: 17,
    pressure: 1014,
  },
  {
    day: "Dziś",
    hour: "8:00",
    weatherName: "rainy",
    temperature: 3,
    rains: 0.4,
    windDirection: 0,
    windSpeed: 16,
    pressure: 1015,
  },
  {
    day: "Dziś",
    hour: "9:00",
    weatherName: "rainy",
    temperature: 5,
    rains: 0.2,
    windDirection: 1,
    windSpeed: 14,
    pressure: 1013,
  },
  {
    day: "Dziś",
    hour: "10:00",
    weatherName: "partlyCloudy",
    temperature: 8,
    rains: 0.2,
    windDirection: 2,
    windSpeed: 9,
    pressure: 1011,
  },
  {
    day: "Dziś",
    hour: "11:00",
    weatherName: "partlyCloudy",
    temperature: 10,
    rains: 0.1,
    windDirection: 3,
    windSpeed: 11,
    pressure: 1011,
  },
  {
    day: "Dziś",
    hour: "12:00",
    weatherName: "sunny",
    temperature: 12,
    rains: 0,
    windDirection: 4,
    windSpeed: 8,
    pressure: 1014,
  },
  {
    day: "Dziś",
    hour: "13:00",
    weatherName: "sunny",
    temperature: 13,
    rains: 0,
    windDirection: 5,
    windSpeed: 7,
    pressure: 1011,
  },
  {
    day: "Dziś",
    hour: "14:00",
    weatherName: "sunny",
    temperature: 12,
    rains: 0,
    windDirection: 6,
    windSpeed: 7,
    pressure: 1006,
  },
  {
    day: "Dziś",
    hour: "15:00",
    weatherName: "partlyCloudy",
    temperature: 10,
    rains: 0,
    windDirection: 4,
    windSpeed: 4,
    pressure: 1006,
  },
  {
    day: "Dziś",
    hour: "16:00",
    weatherName: "partlyCloudy",
    temperature: 10,
    rains: 0,
    windDirection: 0,
    windSpeed: 6,
    pressure: 1007,
  },
  {
    day: "Dziś",
    hour: "17:00",
    weatherName: "cloudy",
    temperature: 8,
    rains: 0,
    windDirection: 1,
    windSpeed: 4,
    pressure: 1005,
  },
  {
    day: "Dziś",
    hour: "18:00",
    weatherName: "cloudy",
    temperature: 7,
    rains: 0,
    windDirection: 2,
    windSpeed: 5,
    pressure: 1005,
  },
  {
    day: "Dziś",
    hour: "19:00",
    weatherName: "rainy",
    temperature: 7,
    rains: 0.8,
    windDirection: 3,
    windSpeed: 8,
    pressure: 1004,
  },
  {
    day: "Dziś",
    hour: "20:00",
    weatherName: "cloudy",
    temperature: 5,
    rains: 0.2,
    windDirection: 4,
    windSpeed: 4,
    pressure: 1006,
  },
  {
    day: "Dziś",
    hour: "21:00",
    weatherName: "cloudy",
    temperature: 5,
    rains: 0,
    windDirection: 5,
    windSpeed: 5,
    pressure: 1008,
  },
  {
    day: "Dziś",
    hour: "22:00",
    weatherName: "cloudy",
    temperature: 4,
    rains: 0,
    windDirection: 6,
    windSpeed: 8,
    pressure: 1009,
  },
  {
    day: "Dziś",
    hour: "23:00",
    weatherName: "cloudy",
    temperature: 4,
    rains: 0,
    windDirection: 7,
    windSpeed: 4,
    pressure: 1009,
  },
  {
    day: "Jutro",
    hour: "00:00",
    weatherName: "cloudy",
    temperature: 3,
    rains: 0,
    windDirection: 7,
    windSpeed: 16,
    pressure: 1008,
  },
  {
    day: "Jutro",
    hour: "01:00",
    weatherName: "cloudy",
    temperature: 2,
    rains: 0,
    windDirection: 6,
    windSpeed: 11,
    pressure: 1010,
  },
  {
    day: "Jutro",
    hour: "02:00",
    weatherName: "snowy",
    temperature: 0,
    rains: 0.3,
    windDirection: 6,
    windSpeed: 6,
    pressure: 1011,
  },
  {
    day: "Jutro",
    hour: "03:00",
    weatherName: "snowy",
    temperature: 1,
    rains: 0.1,
    windDirection: 5,
    windSpeed: 5,
    pressure: 1013,
  },
  {
    day: "Jutro",
    hour: "04:00",
    weatherName: "rainy",
    temperature: 1,
    rains: 0,
    windDirection: 6,
    windSpeed: 6,
    pressure: 1012,
  },
  {
    day: "Jutro",
    hour: "05:00",
    weatherName: "foggy",
    temperature: 2,
    rains: 0,
    windDirection: 7,
    windSpeed: 3,
    pressure: 1014,
  },
  {
    day: "Jutro",
    hour: "06:00",
    weatherName: "foggy",
    temperature: 4,
    rains: 0,
    windDirection: 6,
    windSpeed: 7,
    pressure: 1014,
  },
  {
    day: "Jutro",
    hour: "07:00",
    weatherName: "cloudy",
    temperature: 5,
    rains: 0,
    windDirection: 5,
    windSpeed: 9,
    pressure: 1013,
  },
  {
    day: "Jutro",
    hour: "08:00",
    weatherName: "partlyCloudy",
    temperature: 6,
    rains: 0,
    windDirection: 5,
    windSpeed: 16,
    pressure: 1010,
  },
  {
    day: "Jutro",
    hour: "09:00",
    weatherName: "partlyCloudy",
    temperature: 9,
    rains: 0,
    windDirection: 4,
    windSpeed: 15,
    pressure: 1012,
  },
  {
    day: "Jutro",
    hour: "10:00",
    weatherName: "partlyCloudy",
    temperature: 10,
    rains: 0,
    windDirection: 5,
    windSpeed: 16,
    pressure: 1011,
  },
];
